### ISSUE TITLE
Is it possible to have screenshot in the readme?

### ISSUE THREAD

**Issue by allan-simon** [DGIProject/VideoEditorJS#1]
Hello your project looks very interesting, but for this kind of tools, I think it is very helpful for people to have a screenshot to have a quick glance on what the interface has to propose

you can simply host the image by creating a screenshot folder in your repository and linking the github address of the image in your README

**Comment by landyde** [comment]
Hello, thank you to interest you about our project, we will add screenshot folder soon, now that this project takes a bigger scale.
